In [1]:
import pandas as pd
import numpy as np
import plotly.plotly as py

In [2]:
pretop30 = pd.read_csv('Preterm_top30.csv')
pretermtop30 = pretop30[['CountryName','Preterm ']]
preterm = pretermtop30.rename(columns={'CountryName':'Country'})
preterm = preterm.sort_values(by='Country')
preterm = preterm.reset_index(drop=True)
preterm

                        Country  Preterm
0             Antigua & Barbuda      45.4
1                     Argentina      45.1
2                       Bahamas      49.4
3                      Bulgaria      42.4
4                       Denmark      50.9
5                       Germany      41.4
6                        Greece      54.2
7                       Hungary      56.1
8                       Iceland      53.3
9                         India      43.8
10                    Korea Rep      52.8
11                       Kuwait      46.9
12                   Luxembourg      54.4
13                    Macedonia      71.2
14                        Palau      41.9
15                       Poland      49.3
16                      Romania      43.0
17           Russian Federation      42.3
18                  Saint Lucia      45.6
19                       Serbia      59.6
20                     Slovakia      47.5
21                     Slovenia      54.4
22  St Vincent & the Grenadines      54.4
23                     Suriname      42.1
24                        Tonga      41.4
25                       Turkey      43.5
26                       Tuvalu      41.9
27                      Ukraine      41.3
28               United Kingdom      54.9
29     United States of America      45.5

In [3]:
latlon = pd.read_csv('latitude_longitude.csv')
latlonsorted = latlon.sort_values(by='Country      ')
latlonsorted = latlonsorted[['Country      ','lat','lon']]
latitude_longitude = latlonsorted.rename(columns={'Country      ':'Country'})

latitude_longitude = latitude_longitude.reset_index(drop=True)
latitude_longitude

                               Country        lat         lon
0                    Afghanistan        33.939110   67.709953
1                        Albania        41.153332   20.168331
2                        Algeria        28.033886    1.659626
3                  American Samoa      -14.270972 -170.132217
4                         Angola       -11.202692   17.873887
5                       Anguilla        18.220554  -63.068615
6                     Antarctica       -75.250973   -0.071389
7                Antigua & Barbuda      17.060816  -61.796428
8                      Argentina       -38.416097  -63.616672
9                        Armenia        40.069099   45.038189
10                         Aruba        12.521110  -69.968338
11                     Australia       -25.274398  133.775136
12                       Austria        47.516231   14.550072
13                    Azerbaijan        40.143105   47.576927
14                       Bahamas        25.034280  -77.396280
15                       Bahrain        25.930414   50.637772
16                    Bangladesh        23.684994   90.356331
17                      Barbados        13.193887  -59.543198
18                       Belarus        53.709807   27.953389
19                       Belgium        50.503887    4.469936
20                        Belize        17.189877  -88.497650
21                         Benin         9.307690    2.315834
22                       Bermuda        32.321384  -64.757370
23                        Bhutan        27.514162   90.433601
24                       Bolivia       -16.290154  -63.588653
25          Bosnia and Herzegovina      43.915886   17.679076
26                      Botswana       -22.328474   24.684866
27                  Bouvet Island      -54.423199    3.413194
28                        Brazil       -14.235004  -51.925280
29   British Indian Ocean Territory     -6.343194   71.876519
..                                 ...        ...         ...
214                     Tanzania        -6.369028   34.888822
215                     Thailand        15.870032  100.992541
216                  Timor-Leste        -8.874217  125.727539
217                         Togo         8.619543    0.824782
218                      Tokelau        -8.967363 -171.855881
219                        Tonga       -21.178986 -175.198242
220            Trinidad and Tobago      10.691803  -61.222503
221                      Tunisia        33.886917    9.537499
222                       Turkey        38.963745   35.243322
223                 Turkmenistan        38.969719   59.556278
224        Turks and Caicos Islands     21.694025  -71.797928
225                       Tuvalu        -7.109535  177.649330
226     U.S. Minor Outlying Islands           NaN         NaN
227            U.S. Virgin Islands      18.335765  -64.896335
228                       Uganda         1.373333   32.290275
229                      Ukraine        48.379433   31.165580
230           United Arab Emirates      23.424076   53.847818
231                United Kingdom       55.378051   -3.435973
232        United States of America     37.090240  -95.712891
233                      Uruguay       -32.522779  -55.765835
234                   Uzbekistan        41.377491   64.585262
235                      Vanuatu       -15.376706  166.959158
236                  Vatican City       41.902916   12.453389
237                    Venezuela         6.423750  -66.589730
238                      Vietnam        14.058324  108.277199
239              Wallis and Futuna     -13.768752 -177.156097
240                Western Sahara       24.215527  -12.885834
241                        Yemen        15.552727   48.516388
242                       Zambia       -13.133897   27.849332
243                     Zimbabwe       -19.015438   29.154857

[244 rows x 3 columns]

In [4]:
remove_spaces = [x.strip().replace(' ', ' ') for x in latitude_longitude.Country]
remove_spaces = pd.DataFrame(remove_spaces)
formated = remove_spaces.rename(columns={0:"Country1"})
#formated

In [5]:
new_frame = pd.concat([latitude_longitude,formated],axis=1)
new_frame = new_frame[['Country1','lat','lon']]
#new_frame

In [6]:
country_list =list(preterm.Country)
country_latlon = new_frame.loc[new_frame['Country1'].isin(country_list)]
country_latlon = country_latlon.reset_index(drop=True)
country_latlon

                       Country1        lat         lon
0             Antigua & Barbuda  17.060816  -61.796428
1                     Argentina -38.416097  -63.616672
2                       Bahamas  25.034280  -77.396280
3                      Bulgaria  42.733883   25.485830
4                       Denmark  56.263920    9.501785
5                       Germany  51.165691   10.451526
6                        Greece  39.074208   21.824312
7                       Hungary  47.162494   19.503304
8                       Iceland  64.963051  -19.020835
9                         India  20.593684   78.962880
10                    Korea Rep  40.339852  127.510093
11                       Kuwait  29.311660   47.481766
12                   Luxembourg  49.815273    6.129583
13                    Macedonia  41.608635   21.745275
14                        Palau   7.514980  134.582520
15                       Poland  51.919438   19.145136
16                      Romania  45.943161   24.966760
17           Russian Federation  61.524010  105.318756
18                  Saint Lucia  13.909444  -60.978893
19                       Serbia  44.016521   21.005859
20                     Slovakia  48.669026   19.699024
21                     Slovenia  46.151241   14.995463
22  St Vincent & the Grenadines  12.984305  -61.287228
23                     Suriname   3.919305  -56.027783
24                        Tonga -21.178986 -175.198242
25                       Turkey  38.963745   35.243322
26                       Tuvalu  -7.109535  177.649330
27                      Ukraine  48.379433   31.165580
28               United Kingdom  55.378051   -3.435973
29     United States of America  37.090240  -95.712891

In [7]:
preterm_final = pd.concat([preterm,country_latlon],axis=1)
final = preterm_final[['Country1','Preterm ','lat','lon']]
final.to_csv('Preterm_with_latlon.csv')

In [14]:
df = pd.read_csv('Preterm_with_latlon.csv')
df.head()

df['text'] = df['Country1'] + '<br>Percentage_value ' + (df['Preterm ']).astype(str)

scl = [ [0,"rgb(5, 10, 172)"],[0.35,"rgb(40, 60, 190)"],[0.5,"rgb(70, 100, 245)"],\
    [0.6,"rgb(90, 120, 245)"],[0.7,"rgb(106, 137, 247)"],[1,"rgb(220, 220, 220)"] ]

data = [ dict(
        type = 'scattergeo',
        locationmode = 'IS0-3',
        lon = df['lon'],
        lat = df['lat'],
        text = df['text'],
        mode = 'markers',
        marker = dict( 
            size = 8, 
            opacity = 0.8,
            reversescale = True,
            autocolorscale = False,
            symbol = 'square',
            line = dict(
                width=1,
                color='rgba(102, 102, 102)'
            ),
            colorscale = scl,
            cmin = 0,
            color = df['Preterm '],
            cmax = df['Preterm '].max(),
            colorbar=dict(
                title="Percentage Value for 2015 "
            )
        ))]

layout = dict(
        title = 'Deaths of children under-five years of age due to Preterm<br>(Top 30 countries)',
        colorbar = True,   
        geo = dict(
            scope='World',
            projection=dict( type='Distance Preserving' ),
            showland = True,
            landcolor = "rgb(250, 250, 250)",
            subunitcolor = "rgb(217, 217, 217)",
            countrycolor = "rgb(217, 217, 217)",
            countrywidth = 0.5,
            subunitwidth = 0.5        
        ),
    )

fig = dict( data=data, layout=layout )
py.iplot( fig, validate=False, filename='Cause of death due to Preterm' )

ProxyError: HTTPSConnectionPool(host='plot.ly', port=443): Max retries exceeded with url: /clientresp (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9589d3edd8>: Failed to establish a new connection: [Errno 111] Connection refused',)))